# Generated by Django 6.0.6 on 2026-06-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_badge', models.CharField(default='Youth Day 2026 • Worship · Grow · Become', max_length=120)),
                ('hero_title', models.CharField(default='Youth Day 2026 Raffle Draw', max_length=180)),
                ('hero_tagline', models.CharField(default='WHERE EVERY SOUL MATTERS', max_length=160)),
                ('hero_description', models.TextField(default='Join us as the youth of KAG Clayworks lead the entire Youth Day Sunday service. By purchasing a raffle ticket, you support youth ministry programs while standing a chance to win exciting prizes.')),
                ('primary_cta_text', models.CharField(default='Get Your Ticket', max_length=80)),
                ('secondary_cta_text', models.CharField(default='Payment Instructions', max_length=80)),
                ('hero_callout', models.CharField(default="Limited ticket numbers available. Secure your preferred lucky number before it's taken.", max_length=140)),
                ('ticket_price_note', models.CharField(default='KSh 500 per ticket', max_length=120)),
                ('ticket_goal_note', models.CharField(default='Every ticket helps fund youth ministry activities, discipleship, outreach, and Youth Day initiatives.', max_length=180)),
                ('prize_section_title', models.CharField(default='15+ Winners Will Be Selected', max_length=140)),
                ('prize_section_note', models.CharField(default='The more tickets we sell, the more prizes we add - so spread the word!', max_length=180)),
                ('grand_prize_label', models.CharField(default='Grand Prize', max_length=80)),
                ('grand_prize_name', models.CharField(default='Smart TV', max_length=120)),
                ('grand_prize_description', models.CharField(default='The big one - light up movie nights', max_length=140)),
                ('grand_prize_icon', models.CharField(default='📺', max_length=10)),
                ('grand_prize_image_url', models.URLField(blank=True, default='')),
                ('second_prize_label', models.CharField(default='Second Prize', max_length=80)),
                ('second_prize_name', models.CharField(default='2-Burner Gas Cooker', max_length=120)),
                ('second_prize_description', models.CharField(default='Cook up something delicious', max_length=140)),
                ('second_prize_icon', models.CharField(default='🔥', max_length=10)),
                ('second_prize_image_url', models.URLField(blank=True, default='')),
                ('third_prize_label', models.CharField(default='Third Prize', max_length=80)),
                ('third_prize_name', models.CharField(default='Mobile Phone', max_length=120)),
                ('third_prize_description', models.CharField(default='Stay connected in style', max_length=140)),
                ('third_prize_icon', models.CharField(default='📱', max_length=10)),
                ('third_prize_image_url', models.URLField(blank=True, default='')),
                ('worship_title', models.CharField(default='Worship', max_length=60)),
                ('worship_description', models.CharField(default='Strengthening praise and prayer in every youth gathering.', max_length=160)),
                ('grow_title', models.CharField(default='Grow', max_length=60)),
                ('grow_description', models.CharField(default='Supporting growth in faith, leadership, and community service.', max_length=160)),
                ('become_title', models.CharField(default='Become', max_length=60)),
                ('become_description', models.CharField(default='Helping young people become confident, compassionate leaders.', max_length=160)),
                ('support_title', models.CharField(default='Need Assistance?', max_length=120)),
                ('support_description', models.TextField(default='If you experience any difficulties with payment, registration, ticket selection, or downloading your ticket, please contact the Youth Secretariat.')),
                ('support_phone', models.CharField(default='+254 715 550 805', max_length=30)),
                ('faq_payment_answer', models.TextField(default='Pay KSh 500 via CoopBank to the official details on the payment instructions page, then submit your confirmation SMS when registering.')),
                ('faq_draw_answer', models.TextField(default='The draw takes place during the Youth Day Sunday service. Winners will be selected live and announced to the congregation.')),
                ('faq_more_tickets_answer', models.TextField(default='Yes. Each additional ticket increases your chance of winning and your support for the youth ministry.')),
                ('faq_proceeds_answer', models.TextField(default='All proceeds go directly toward KAG Clayworks Youth Ministry programs - discipleship materials, outreach events, camps, and Royal Rangers activities.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Content',
                'verbose_name_plural': 'Landing Page Content',
            },
        ),
    ]
