# Generated by Django 6.0.6 on 2026-06-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('ADMIN', 'Admin')], db_index=True, default='SECRETARY', max_length=20),
        ),
    ]
