# Generated by Django 6.0.6 on 2026-06-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('PRINTED', 'Printed'), ('COLLECTED', 'Collected'), ('WON', 'Won')], default='GENERATED', max_length=20)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.raffleevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='members.member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='payments.payment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'ticket_number'), name='unique_ticket_per_event')],
            },
        ),
    ]
